# CraftHeads Configuration File

# This enables the check for updates.
# If this is set to true, you will get notifications about updates.
# If don't want to check for updates, set this to false.
update-check: true

# This enables metrics.
# If you don't want metrics enabled set this to false.
metrics: true

# This enables economy support for selling heads
# This option requires the Vault plugin and an economy plugin
economy: false

# This is the default price for heads that don't have a price above zero
# You can set this to zero to make them free by default
# Only works when economy is enabled
default-price: 100

# This is the price the player has to pay to buy his own head
# You can set this to zero to make it by default
# Only works when economy is enabled
player-own-head-price: 100

# This is the price the player has to pay to buy other player's heads
# You can set this to zero to make it by default
# Only works when economy is enabled
player-other-head-price: 100

# This tells the plugin if it's supposed to reset the category files to the ones that come bundled with the plugin
# If this is true, when the server loads, the default categories will be extracted to the "categories" folder
# This will overwrite any files in the "categories" folder that have the same name as the default ones
# After the categories are reset, this value will be automatically set to false
reset-categories: true